### ISSUE TITLE
Failed to run on openSUSE 13.1 (x64)

### ISSUE THREAD

**Issue by skvggor** [passcod/twd#2]
Hello, 
I tried to run the app (via clone and bin), but it fails and I ~~don't~~ know how I can help to solve this.

Below a picture of my terminal when I try to run.
![tela-twd-terminal](https://cloud.githubusercontent.com/assets/958723/4030241/e1c7d1e0-2c5a-11e4-8ff0-afb2096c86b3.jpg)

**Comment by passcod** [comment]
_Did you mean "I **want to** know how I can help…" or really "I know how I can help"? If it is the latter, please do share! :)_

Observations:
- The app is being loaded, parsed, and executed, as evidenced by the `INFO:CONSOLE` lines.
- The `ERROR:platform_thread_linux.cc` line about nice [seems to also be a Chromium bug](https://code.google.com/p/chromium/issues/detail?id=252143), which might hint at it being in WebKit or something similar, but shouldn't be fatal.
- The `Not implemented reached in virtual int disk_cache` lines are a known bug of node-webkit (rogerwang/node-webkit#1258) and are not fatal.
- The `NVCtrl` line is often encountered and seems to be mostly benign.

Questions:
- Does that really fail? I don't see the command exiting, I wonder if that is just a sample of what appears. Is there more below?
- What is the version of node-webkit on your system?
- Is it the latest you can get through openSuSE? Can you update it and try again otherwise?

**Comment by skvggor** [comment]
The app works now! 
I was with version `0.8.6` of the node-webkit and updated to `0.10.2` and everything went as expected.

Thanks for attention and sorry for the misunderstanding (in my sentence above - missed the "don't").

**Comment by passcod** [comment]
I'll make a note on the README that node-webkit => 0.10 is necessary, then. Thank you for the report!
